Setup: Hw setup is fully made through python;
IObundle/iob-lib pull request #365
Opened 2022-12-30 15:45 UTC by PedroAntunes178

2023-01-02 15:27 UTC, arturum1 requested changes
I suggest merging the PR https://github.com/PedroAntunes178/iob-lib/pull/1.
This PR includes the changes I mentioned.

2023-01-02 15:27 UTC, arturum1 commented on scripts/ios.py
> +        if (instance['type'] not in port_list) and (instance['type'] in submodules["hw_setup"]["hw_modules"]):
I implemented this change in https://github.com/PedroAntunes178/iob-lib/pull/1

2023-01-02 15:27 UTC, arturum1 commented on scripts/createSystem.py
> +            sub_dir = f"{core_dir}/submodules/{instance['type']}"
I reverted some of these changes in https://github.com/PedroAntunes178/iob-lib/pull/1. This way we keep the 
`submodule_dirs` dictionary in most functions, allowing configurable submodule directories.

If we want to hard code the submodules to the `{core_dir}/submodules/{instance['type']}` path we can do it by creating a `dirs` dictionary in *_setup.py with these path names.
I added the `dirs` dictionary with these path names in https://github.com/PedroAntunes178/iob-soc/pull/3.

2023-01-02 16:43 UTC, PedroAntunes178 commented on scripts/ios.py
> +        if (instance['type'] not in port_list) and (instance['type'] in submodules["hw_setup"]["hw_modules"]):
I agree with this change.
Could you use iob_colors.py in the text to make the exception stand out? To do so, you only need to include iob_colors and add {iob_colors.FAIL} in the beginning of the string and {iob_colors.ENDC} to the end.

2023-01-02 17:07 UTC, PedroAntunes178 commented on scripts/createSystem.py
> +            sub_dir = f"{core_dir}/submodules/{instance['type']}"
Relatively to the submodule's dir, I think by default all submodules could be considered to be in ./submodules/MODULE_NAME
If it is necessary to overwrite its directory, a dictionary named 'custom_dirs' could be added to meta.
Then the directories could be accessed with `meta['custom_dirs']['MODULE_NAME']`. 
When adding a submodule, the setup would first see if `./submodules/MODULE_NAME` is a directory. If not, it would check if `MODULE_NAME` is a key in the `meta['custom_dirs']` and use the str corresponding to the directory if so happens. If not it could either raise an error or in the case of hw_setup function it would look in LIB hardware to see if the module exists there.

2023-01-02 17:11 UTC, arturum1 commented on scripts/ios.py
> +        if (instance['type'] not in port_list) and (instance['type'] in submodules["hw_setup"]["hw_modules"]):
Done. https://github.com/PedroAntunes178/iob-lib/pull/1/commits/1809abd81186167ae402d8c2f246f30b4d9e339e

2023-01-03 02:56 UTC, arturum1 commented on scripts/createSystem.py
> +            sub_dir = f"{core_dir}/submodules/{instance['type']}"
In commit https://github.com/PedroAntunes178/iob-lib/pull/1/commits/73999b3e8d06cb97a703ed281246fef277dc0311 I've added the `build_srcs.set_default_submodule_dirs()` function to auto-fill any non defined directory with the respective submodule's default directory .

This allows the user to define a `dirs` dictionary in the `meta['submodules']` dictionary of the `*_setup.py` file to override any submodule directory. If the `dirs` dictionary is not defined, it will be created automatically with default values.

2023-01-03 16:17 UTC, PedroAntunes178 commented
@jjts PR reviewed

2023-01-03 23:53 UTC, merged