Fix `axis2axi`; Update `reserved_signals` connections.
IObundle/iob-lib pull request #651
Opened 2023-08-25 14:44 UTC by arturum1

2023-08-26 11:04 UTC, jjts requested changes
Style and linter related issues

2023-08-26 11:04 UTC, jjts commented on hardware/modules/axis2axi/hardware/src/axis2axi_in.v
> +      .rst_i(state == WAIT_DATA),
Ports should not have logic

Ths fsm should produce this control signal as an output

2023-08-26 11:04 UTC, jjts commented on hardware/modules/axis2axi/hardware/src/axis2axi_in.v
> +   parameter BUFFER_W   = BURST_W + 1
Useless parameter

2023-08-26 17:16 UTC, arturum1 commented on hardware/modules/axis2axi/hardware/src/axis2axi_in.v
> +   parameter BUFFER_W   = BURST_W + 1
I only added the `BUFFER_W` parameter because it is used in the port list. The Verilog localparameters cannot be used in the port list.
Either way, in commit [e47a7fe](https://github.com/IObundle/iob-lib/pull/651/commits/e47a7fec44a2f40d7766a2176ba37bed376e272a) I removed that parameter and used its value `BURST_W + 1` instead in the port list.

2023-08-26 17:25 UTC, arturum1 commented on hardware/modules/axis2axi/hardware/src/axis2axi_in.v
> +      .rst_i(state == WAIT_DATA),
Does that apply to the other ports, including the enable port of that register?
`      .en_i(state == TRANSFER && transfer),`

Should I create wires like this:
`wire transfer_count_reg_en = state == TRANSFER && transfer;`
And then use the port:
`      .en_i(transfer_count_reg_en),`

2023-08-26 18:47 UTC, jjts commented on hardware/modules/axis2axi/hardware/src/axis2axi_in.v
> +      .rst_i(state == WAIT_DATA),
It applies to any ports 

reg transfer_count_reg_en

Then go to the FSM case statement
transfer_count_reg_en = 1'b0
case (TRANSFER) begin
...
transfer_count_reg_en 1'b1;
...

2023-08-26 18:47 UTC, jjts commented on hardware/modules/axis2axi/hardware/src/axis2axi_in.v
> +   parameter BUFFER_W   = BURST_W + 1
BURST_W + 1  is fine, it is what I meant

2023-08-26 19:08 UTC, arturum1 commented on hardware/modules/axis2axi/hardware/src/axis2axi_in.v
> +      .rst_i(state == WAIT_DATA),
I cannot make the `transfer_count_reg_en` dependent only on the FSM.
Note that the `transfer_count_reg_en` also depends on the `transfer` (that does not come from the FSM).

The `transfer` signal is defined as:
`   wire transfer = axi_wready_i && axi_wvalid_o;`

2023-08-26 19:11 UTC, arturum1 commented on hardware/modules/axis2axi/hardware/src/axis2axi_in.v
> +      .rst_i(state == WAIT_DATA),
I understand that the `state == TRANSFER` could be moved to the FSM, but the part `&& transfer` cannot.

With this in mind, should I make the wire:
`wire transfer_count_reg_en = state == TRANSFER && transfer;`
And then use the port:
`      .en_i(transfer_count_reg_en),`

I could replace the `state == TRANSFER` with a new signal that comes from the FSM, but I would still need the `transfer_count_reg_en` wire because of the `&& transfer` part.

2023-08-26 22:42 UTC, jjts commented on hardware/modules/axis2axi/hardware/src/axis2axi_in.v
> +      .rst_i(state == WAIT_DATA),
This is equivalent :

case (TRANSFER) begin
...
transfer_count_reg_en = transfer;

Normally there is one or 2 places where state is checked : to compute next state and to compute FSM outputs 

No more.

2023-08-26 23:51 UTC, arturum1 commented on hardware/modules/axis2axi/hardware/src/axis2axi_in.v
> +      .rst_i(state == WAIT_DATA),
Refactored code as requested in https://github.com/IObundle/iob-lib/pull/651/commits/69f6247232adc1327fb0b885cdd5dc436a7c28c4

2023-09-05 00:03 UTC, jjts commented
Iob-lib must get rid of everything that is soc related

2023-09-13 01:32 UTC, jjts commented on scripts/ios.py
> +    ), f"{iob_colors.FAIL}Port '{port_name}' of interface '{if_name}' for peripheral '{peripheral_instance.name}' not mapped!{iob_colors.ENDC}"
Iob-lib does not deal with peripherals

Iob-soc does

2023-09-21 20:21 UTC, merged